Repository CS2113-AY1819S1-T12-1/main, pull requests merged in 2018-11, with the labels that each got.

#117 [v1.4] Update UG and DG for authentication
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.high

#114 [v1.4] Fix admin authentication
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: priority.high

#120 [V1.4] Modify export command to export current user registered event
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/ExportCalendarCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/AttendanceContainsUserPredicate.java
  src/test/data/sandboxmanyPersons.xml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/SignupCommandTest.java
Labels: priority.high

#122 Update Project Portfolio and UG, DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/Tertium3.adoc
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: priority.high

#156 [Request Merge]Adding integration tests
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommentCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommentCommand.java
  src/main/java/seedu/address/logic/commands/ReplyCommentCommand.java
  src/main/java/seedu/address/logic/comments/AddComment.java
  src/main/java/seedu/address/logic/comments/CommentFacade.java
  src/main/java/seedu/address/logic/comments/Comments.java
  src/main/java/seedu/address/logic/comments/DeleteComment.java
  src/main/java/seedu/address/logic/comments/ReplyComment.java
  src/main/java/seedu/address/logic/comments/dummy.html
  src/main/java/seedu/address/logic/parser/AddCommentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommentCommandParser.java
  src/main/java/seedu/address/logic/parser/ReplyCommentCommandParser.java
  src/test/java/seedu/address/logic/commands/AddCommentCommandTest.java
  src/test/java/seedu/address/logic/commands/CommentAssertion.java
  src/test/java/seedu/address/logic/commands/DeleteCommentCommandTest.java
  src/test/java/seedu/address/logic/commands/ReplyCommentCommandTest.java
  src/test/java/seedu/address/logic/comments/CommentFacadeTest.java
  src/test/java/systemtests/CommentCommandSystemTest.java
Labels: priority.high

#155 [v1.4] Resolve issues released in PE-1
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/SignupCommand.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/LogoutCommandTest.java
  src/test/java/seedu/address/logic/commands/SignupCommandTest.java
Labels: priority.high

#166 Implemented Attending command
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AttendingCommand.java
  src/main/java/seedu/address/logic/parser/EventManagerParser.java
  src/main/java/seedu/address/model/event/EventContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: priority.high, type.story

#124 [V1.4] Testing for export calendar command
  build.gradle
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ExportCalendarCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ExportCalendarCommandParser.java
  src/main/java/seedu/address/model/event/AttendanceContainsUserPredicate.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
  src/test/data/XmlSerializableEManagerTest/typicalEventsEventManager.xml
  src/test/java/seedu/address/logic/commands/ExportCalendarCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCalendarCommandParserTest.java
  src/test/java/seedu/address/model/event/AttendanceContainsUserPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/EventManagerSystemTest.java
  src/test/java/systemtests/ExportCalendarCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.high, status.ongoing

#168 [V1.3]Auto-updating status
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/UpdateStatusCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EventManagerParser.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Status.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/data/XmlEventManagerStorageTest/invalidAndValidEventEventManager.xml
  src/test/data/XmlEventManagerStorageTest/invalidEventEventManager.xml
  src/test/data/XmlSerializableEManagerTest/duplicateEventEventManager.xml
  src/test/data/XmlSerializableEManagerTest/invalidEventEventManager.xml
  src/test/data/XmlSerializableEManagerTest/typicalEventsEventManager.xml
  src/test/data/XmlUtilTest/invalidEventField.xml
  src/test/data/XmlUtilTest/missingEventField.xml
  src/test/data/XmlUtilTest/validEvent.xml
  src/test/data/XmlUtilTest/validEventManager.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/event/StatusTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/EventListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EventManagerSystemTest.java
Labels: priority.high, type.enhancement

#169 [V1.4]Fix some issue with language display and Date allow overflow
  src/main/java/seedu/address/model/DateTimeUtil.java
  src/main/java/seedu/address/model/event/DateTime.java
  src/test/java/seedu/address/model/event/DateTimeTest.java
Labels: priority.medium, status.ongoing, type.bug

#171 Update PPP
  docs/team/tertium3.adoc
Labels: priority.high

#172 [V1.4]Updated Test Cases for UpdateStatusCommand
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/EventManagerChangedEvent.java
  src/main/java/seedu/address/logic/commands/UpdateStatusCommand.java
  src/main/java/seedu/address/model/attendee/Attendee.java
  src/main/java/seedu/address/model/event/Comment.java
  src/main/java/seedu/address/model/event/Contact.java
  src/main/java/seedu/address/model/event/Status.java
  src/main/java/seedu/address/model/event/Venue.java
  src/main/java/seedu/address/storage/XmlAdaptedAttendee.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateStatusCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EventManagerParserTest.java
  src/test/java/seedu/address/model/event/ContactTest.java
  src/test/java/seedu/address/model/event/StatusTest.java
  src/test/java/seedu/address/model/event/VenueTest.java
Labels: priority.high, type.task

#174 [V1.4] Added Event Reminder
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/ui/SendEventReminder.java
  src/main/java/seedu/address/logic/commands/ReminderCommand.java
  src/main/java/seedu/address/logic/commands/UpdateStatusCommand.java
  src/main/java/seedu/address/logic/parser/EventManagerParser.java
  src/main/java/seedu/address/model/DateTimeUtil.java
  src/main/java/seedu/address/model/event/EventContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/logic/parser/EventManagerParserTest.java
Labels: priority.high, type.enhancement

#177 [V1.4]Updated SampleData & Test for ReminderCommand
  src/main/java/seedu/address/logic/commands/ReminderCommand.java
  src/main/java/seedu/address/model/DateTimeUtil.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RegisterCommandTest.java
  src/test/java/seedu/address/logic/commands/ReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/UpdateStatusCommandTest.java
Labels: priority.high, type.task

#181 [V1.4]Revised UpdateStatusCommand and added author tags
  src/main/java/seedu/address/logic/commands/UpdateStatusCommand.java
  src/main/resources/view/EventSearchPage.html
  src/test/java/seedu/address/model/attendee/AttendeeTest.java
Labels: priority.medium, severity.low

#183 Fix file path bug and update for UG DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/ExportCalendarCommand.java
  src/main/java/seedu/address/logic/parser/ExportCalendarCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ExportCalendarCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCalendarCommandParserTest.java
  src/test/java/systemtests/ExportCalendarCommandSystemTest.java
Labels: priority.high, status.ongoing, type.bug

#184 Update About Us and Image format
  docs/AboutUs.adoc
  docs/images/tertium3.png
Labels: priority.high

#185 Try to fix export command
  src/main/java/seedu/address/logic/commands/ExportCalendarCommand.java
Labels: priority.high

#187 Minor changes
  src/main/java/seedu/address/MainApp.java
Labels: severity.low
