Repository CS2113-AY1819S1-T12-1/main, pull requests merged in 2018-10, with the labels that each got.

#19 [WIP][v1.1] Login stub function
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EventManagerParser.java
  src/main/java/seedu/address/logic/parser/LoginCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/user/Password.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/model/user/Username.java
  src/main/java/seedu/address/storage/JsonUserStorage.java
  src/main/java/seedu/address/storage/UserStorage.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  users.json
Labels: priority.high

#46 [v1.2] DG Authentication implementation details
  docs/DeveloperGuide.adoc
Labels: type.task

#39 [WIP][v1.2] JSON parsing and admin access rights
  build.gradle
  docs/DeveloperGuide.adoc
  docs/team/jamesyaputra.adoc
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/logic/parser/EventManagerParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserAccount.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/storage/JsonUserStorage.java
  src/main/java/seedu/address/storage/UserStorage.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.high, type.enhancement

#50 Adding an addCommand INDEX C/STRING
  src/main/java/seedu/address/logic/commands/AddCommentCommand.java
  src/main/java/seedu/address/logic/parser/AddCommentCommandParser.java
  src/main/java/seedu/address/logic/parser/EventManagerParser.java
Labels: priority.high, type.task

#52 [v1.2] Fixed auth-model linkage & added logout command test
  build.gradle
  docs/images/Ui.png
  docs/images/damithc.jpg
  docs/images/james.jpg
  docs/images/lejolly.jpg
  docs/images/m133225.jpg
  jsoup-1.11.3.jar
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/LogoutCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserAccount.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/LogoutCommandTest.java
Labels: priority.medium, type.task

#59 [Request to merge][v1.3] Writing Test Cases
  src/test/java/seedu/address/logic/comments/AddCommentTest.java
  src/test/java/seedu/address/logic/comments/DeleteCommentTest.java
  src/test/java/seedu/address/logic/comments/ReplyCommentTest.java
Labels: priority.high, type.task

#60 [v1.3] User getter
  src/main/java/seedu/address/model/UserAccount.java
Labels: priority.medium

#64 [WIP][v1.3] Updating authentication
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserAccount.java
  src/main/java/seedu/address/model/event/Email.java
  src/main/java/seedu/address/model/user/Password.java
  src/main/java/seedu/address/model/user/Username.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.high, type.enhancement

#74 [v1.3] Add tests for authentication classes
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/SignupCommand.java
  src/main/java/seedu/address/model/user/Password.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/storage/JsonUserStorage.java
  src/main/java/seedu/address/storage/UserStorage.java
  src/main/resources/comments/60.html
  src/main/resources/comments/61.html
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/SignupCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/LoginCommandParserTest.java
  src/test/java/seedu/address/logic/parser/SignupCommandParserTest.java
  src/test/java/seedu/address/model/user/PasswordTest.java
  src/test/java/seedu/address/model/user/UserTest.java
  src/test/java/seedu/address/model/user/UsernameTest.java
  src/test/java/seedu/address/testutil/TypicalUsers.java
  src/test/java/seedu/address/testutil/UserBuilder.java
Labels: priority.high, type.task

#81 [v1.3] Add my updates for the UG, DG and my project portfolio
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/AuthenticationDiagram.png
  docs/team/jamesyaputra.adoc
Labels: priority.high

#82 [WIP]Adding Comments field
  src/main/java/seedu/address/model/event/Comments.java
  src/test/java/seedu/address/model/event/CommentsTest.java
Labels: priority.high

#84 [v1.3] Optimise authentication commands
  .gitignore
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/SignupCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserSession.java
  src/main/java/seedu/address/storage/JsonUserStorage.java
  src/main/java/seedu/address/storage/UserStorage.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/SignupCommandTest.java
Labels: priority.medium, type.task

#87 [V1.3]WIP Event Reminder
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/event/Comment.java
  src/main/java/seedu/address/model/event/DateTime.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/Phone.java
  src/main/java/seedu/address/model/event/Status.java
  src/main/java/seedu/address/storage/Comments.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/java/seedu/address/ui/EventPageFormatter.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EventListCard.fxml
  src/test/data/XmlEventManagerStorageTest/NotXmlFormatEventManager.xml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/EventManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/VersionedEventManagerTest.java
  src/test/java/seedu/address/model/event/CommentTest.java
  src/test/java/seedu/address/model/event/CommentsTest.java
  src/test/java/seedu/address/model/user/PasswordTest.java
  src/test/java/seedu/address/model/user/UsernameTest.java
  src/test/java/seedu/address/storage/XmlEventManagerStorageTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/EventManagerSystemTest.java
Labels: priority.high, status.ongoing, type.story, type.task

#89 [v1.3] Password encryption using PBKDF2WithHmacSHA1
  out/production/resources/view/EventListCard.fxml
  src/main/java/seedu/address/commons/util/PasswordUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserSession.java
  src/main/java/seedu/address/storage/JsonUserStorage.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/SignupCommandTest.java
Labels: priority.high, type.enhancement

#91 [V1.3][Completed]Comment field test support
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/event/Comment.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedEvent.java
  src/test/data/XmlEventManagerStorageTest/invalidAndValidEventEventManager.xml
  src/test/data/XmlEventManagerStorageTest/invalidEventEventManager.xml
  src/test/data/XmlSerializableEManagerTest/duplicateEventEventManager.xml
  src/test/data/XmlSerializableEManagerTest/invalidEventEventManager.xml
  src/test/data/XmlSerializableEManagerTest/typicalEventsEventManager.xml
  src/test/data/XmlUtilTest/invalidEventField.xml
  src/test/data/XmlUtilTest/missingEventField.xml
  src/test/data/XmlUtilTest/validEvent.xml
  src/test/data/XmlUtilTest/validEventManager.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/event/CommentTest.java
  src/test/java/seedu/address/storage/XmlAdaptedEventTest.java
  src/test/java/seedu/address/testutil/EditEventDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/seedu/address/testutil/TypicalEvents.java
  src/test/java/systemtests/SampleDataTest.java
Labels: priority.high, type.task

#96 [v1.3] Export command, UGDG update, and minor modification
  build.gradle
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Tertium3.jpg
  src/main/java/seedu/address/logic/commands/ExportCalendarCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EventManagerParser.java
  src/main/java/seedu/address/logic/parser/ExportCalendarCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/DateTimeManager.java
  src/main/java/seedu/address/model/DateTimeUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/EventContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/logic/commands/ExportCalendarCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCalendarCommandParserTest.java
  src/test/java/seedu/address/model/event/EventContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/EventManagerSystemTest.java
  src/test/java/systemtests/ExportCalendarCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.high, status.ongoing, type.enhancement

#106 [v1.3] Update user session
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/model/UserSession.java
Labels: priority.high

#105 [Merge Code please]Adding comments to the Browserpanel
  _reposense/config.json
  src/main/java/seedu/address/logic/commands/AddCommentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommentCommand.java
  src/main/java/seedu/address/logic/commands/ReplyCommentCommand.java
  src/main/java/seedu/address/logic/comments/AddComment.java
  src/main/java/seedu/address/logic/comments/Comments.java
  src/main/java/seedu/address/logic/comments/DeleteComment.java
  src/main/java/seedu/address/logic/comments/ReplyComment.java
  src/main/java/seedu/address/logic/comments/dummy.html
  src/main/java/seedu/address/logic/parser/AddCommentCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommentCommandParser.java
  src/main/java/seedu/address/logic/parser/ReplyCommentCommandParser.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/EventCard.java
  src/main/resources/view/EventSearchPage.html
  src/test/data/sandboxmanyPersons.xml
  src/test/java/guitests/guihandles/EventCardHandle.java
  src/test/java/seedu/address/logic/comments/AddCommentTest.java
  src/test/java/seedu/address/logic/comments/DeleteCommentTest.java
  src/test/java/seedu/address/logic/comments/ReplyCommentTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/EventManagerSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.high, type.task

#109 [v1.3] Temp fix for BrowserPanel display issue and tests for RegisterCommand
  .travis.yml
  build.gradle
  docs/EventSearchPage.html
  src/main/java/seedu/address/logic/commands/RegisterCommand.java
  src/main/java/seedu/address/logic/commands/UnregisterCommand.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/logic/commands/RegisterCommandTest.java
  src/test/java/seedu/address/logic/commands/UnregisterCommandTest.java
  src/test/java/seedu/address/logic/parser/RegisterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnregisterCommandParserTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
  src/test/java/systemtests/EventManagerSystemTest.java
Labels: priority.high, severity.high, type.bug, type.task

#111 [V1.3] New Find Command with test case
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/event/EventContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/EventManagerParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/event/EventContainsKeywordsPredicateTest.java
  src/test/java/systemtests/EventManagerSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.high, status.ongoing

#92 [v1.3] Integrate authentication into all commands and edit test cases
  README.adoc
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddCommentCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RegisterCommand.java
  src/main/java/seedu/address/logic/commands/ReplyCommentCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/comments/dummy.html
  src/main/java/seedu/address/model/UserSession.java
  src/test/java/guitests/guihandles/EventCardHandle.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/HistoryCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/RegisterCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/EventManagerSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.high, status.ongoing, type.task
